start_minimized: false
key_timeout: 3
play_queue_size: 3
record_queue_size: 3
use_keyboard: true
use_mouse: true
use_mouse_wheel: true
use_gui: true
default_playback_delay: 0.05
default_listen_during_playback: true
default_record_delay: false
default_record_mouse_movement: false
default_record_mouse_fps: 30
default_playback_speed: 1.0
default_macro_cooldown: 1.0
macro_0:
  name: Record
  filename: strategems/record.json
  play_hotkey: f2
  record_hotkey: alt+ctrl+f2
  listen_during_playback: false
  record_delay: true
  record_mouse_movement: true
  record_mouse_fps: 10
  cooldown: 2.0
macro_1:
  name: Reinforcement
  filename: strategems/basic/reinforce.json
  play_hotkey: f1|alt+mouse_wheel_down
macro_2:
  name: Resupply
  filename: strategems/basic/resupply.json
  play_hotkey: f6|alt+mouse_wheel_up
macro_3:
  name: Support Weapon
  filename: strategems/support weapon/laser cannon.json
  play_hotkey: f7
macro_4:
  name: Backpack
  filename: strategems/support weapon/watchdog rover.json
  play_hotkey: f8
macro_5:
  name: Sentry
  filename: strategems/sentry/rocket sentry.json
  play_hotkey: f9|mouse_x
macro_6:
  name: Airstrike
  filename: strategems/eagle/eagle napalm airstrike.json
  play_hotkey: f10|mouse_x2
macro_7:
  name: SEAF Artillery
  filename: strategems/basic/seaf artillery.json
  play_hotkey: f11
