key_delay: 0.05
key_timeout: 30
default_listen_during_playback: true
macro_default_cooldown: 1.0
play_queue_size: 1
record_queue_size: 1
use_keyboard: true
use_mouse: true

macro_0:
  name: Record
  play_hotkey: f2
  record_hotkey: alt+ctrl+f2
  filename: strategems/record.json
  cooldown: 2.0
  listen_during_playback: false

macro_1:
  name: Reinforcement
  play_hotkey: f1
  filename: strategems/basic/reinforce.json

macro_2:
  name: Resupply
  play_hotkey: f6
  filename: strategems/basic/resupply.json

macro_3:
  name: Laser Canon
  play_hotkey: f7
  filename: strategems/support weapon/laser cannon.json

macro_4:
  name: Watchdog Rover
  play_hotkey: f8
  filename: strategems/support weapon/watchdog rover.json

macro_5:
  name: Rocket Sentry
  play_hotkey: f9
  filename: strategems/sentry/rocket sentry.json

macro_6:
  name: Eagle Cluster Bomb
  play_hotkey: f10
  filename: strategems/eagle/eagle cluster bomb.json

macro_7:
  name: Reinforcement
  play_hotkey: mouse_x
  filename: strategems/basic/reinforce.json

macro_8:
  name: Eagle Cluster Bomb
  play_hotkey: mouse_x2
  filename: strategems/eagle/eagle cluster bomb.json